---
title: "Recorder Feedback Example Email"
params:
    recipient_name: ""
    recipient_email: "UNKNOWN"
    focal_data: ""
    bg_data: ""
    focal_computed_objects: ""
    bg_computed_objects: ""
    content_key: ""
    config: ""
    extra_params: ""
footer-date-time: "`r  format(Sys.time(), '%Y-%m-%d %H:%M:%S %Z')`"
recipient-email: "`r params$recipient_email`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = FALSE, 
                      fig.align = 'center',
                      error=F,
                      results='asis')
```

```{r, eval=FALSE}
# These R chunks is where you define the content of your email.
# Load in the params object, which contains all the R objects passed to the email:
# e,g. params$focal_data, params$bg_data, etc.
# You can use params$recipient_name, params$recipient_email, etc. to personalise the email.
```

# Hello `r params$recipient_name`!

Look at your data:

```{r}
knitr::kable(params$focal_data)
```

Computed objects from the focal data:

```{r}
params$focal_computed_objects
```

Best wishes,
recorderFeedback
